### ISSUE TITLE
[TODO] Board Area Rects

### ISSUE THREAD

**Issue by Bratah123** [BAA-Studios/MOOgiwara#15]
## Abstract
This purpose of this issue is to map out where each area of the map is see: [code](https://github.com/BAA-Studios/MOOgiwara/blob/main/client/src/handlers/game_handler.ts)

Each rectangle is like a hitbox or collider that we will use to render and figure out where cards should be played.

## Details
The coordinates should be filled out accordingly.
The color of the boxes should be invisible (not visible): Think of them as invisible hit boxes.

We will be able to uses this rectangles to indicate to players that the cards they are dragging can be played there as a flashing transparent green.

## Images
See each area's location
![image](https://user-images.githubusercontent.com/58405975/206334962-6bc912f7-379e-4da0-afb6-57a18e604678.png)

Our game's board can be seen [here](https://github.com/BAA-Studios/MOOgiwara/blob/main/client/public/images/moogiwara_game_board.png)
Please use it to map the boxes!

## Tasks
- [x] Player Character Area
- [x] Opponent Character Area
- [x] Player Hand Area
- [x] Opponent Hand Area
- [x] Player Deck Area
- [x] Opponent Deck Area
- [x] Player Trash Area
- [x] Opponent Trash Area
- [x] Opponent Deck Area
- [x] Player Leader Area
- [x] Opponent Leader Area
- [x] Player Don Area
- [x] Opponent Don Area
- [x] Player Don Deck Area
- [x] Opponent Don Deck Area
- [x] Player Life Area
- [x] Opponent Life Area

**Comment by Bratah123** [comment]
UPDATE: New board UI incoming, do not start this issue until Issue: https://github.com/BAA-Studios/MOOgiwara/issues/23 is resolved!
