### ISSUE TITLE
[TODO] Loading screen

### ISSUE THREAD

**Issue by KOOKIIEStudios** [BAA-Studios/MOOgiwara#16]
## Abstract
Due to the large images, we will require a loading screen for when the app first starts.

## Tasks
- [ ] Sprite sheet: straw hat that stretches and bounces back to original shape
- [ ] Render the loading screen on top of the main screen, once data arrives we can destroy the loading screen
- [ ] Foley
- [ ] Sound effect for completion
