### ISSUE TITLE
[TODO] Deck saving

### ISSUE THREAD

**Issue by KOOKIIEStudios** [BAA-Studios/MOOgiwara#18]
## Abstract
Allow users to save decks on the server, after logging in (see #17)

## Details
We should probably use MongoDB to allow horizontal scaling, should the player-base grow large

## Tasks
- [ ] Set up a MongoDB system
- [ ] Document set-up instructions
- [ ] Test deploy
- [ ] Test GSI integration
