### ISSUE TITLE
[TODO] Button Coloring

### ISSUE THREAD

**Issue by Bratah123** [BAA-Studios/MOOgiwara#19]
## Abstract
Make the buttons have a tint when the mouse is hovering over a button.

The "Create Deck" and "Options" button don't seem to have a tint when clicked or hovered over.

## Tasks
- [ ] Hover Color for "Play" Button
- [ ] Click/Hover Color for "Create Deck"
- [ ] Click/Hover Color "Options"

**Comment by KOOKIIEStudios** [comment]
hover was intentionally left out because the cursor already changes to a hand while hovering - this can be added
clicking not being visibly tinted for hollow buttons is a bug
