### ISSUE TITLE
[TODO] Update server `package.json`

### ISSUE THREAD

**Issue by KOOKIIEStudios** [BAA-Studios/MOOgiwara#21]
## Abstract
Some of the packages used are a few years old, and should probably be updated to their latest versions to reduce technical debt down the line.

As such, we might as well overhaul `package.json` and update everything while we're at it

## Tasks
- [x] socket.io 2.3.0 -> 4.5.4
- [x] express 4.17.1 -> 4.18.2
- [x] nodemon 2.0.2 -> 2.0.20
- [x] Re-configure project metadata (name, author, etc)
- [x] Remove unused script alias (test)
- [x] Set license to AGPL v3 - AGPL v2 does not exist; GPL v2 is not compatible with AGPL v3 (repo license)
