### ISSUE TITLE
[TODO] Main Menu: Create Lobby Button

### ISSUE THREAD

**Issue by Bratah123** [BAA-Studios/MOOgiwara#30]
## Abstract
This creates a button in the Main Menu that allows users to make a custom Lobby. The Lobby ID should be randomly generated.

## Details
This puts the user into a queue with a given randomized Lobby ID. 
Other players can join the lobby by typing in that lobby id.

## Tasks
- [ ] Add Button to Menu
- [ ] Loading Screen/Intermission (display the lobby id)
- [ ] Server-side changes to create custom `Game` instances rather than than the auto-generated ones.
