### ISSUE TITLE
[TODO] Game Board: Right Clicking Cards

### ISSUE THREAD

**Issue by Bratah123** [BAA-Studios/MOOgiwara#33]
## Abstract
Right Clicking cards should bring up a larger readable version of the card clicked.
This is implemented in many online card games, ssee LoR Below.

## Examples:
LoR card display after right clicking
![image](https://user-images.githubusercontent.com/58405975/208010185-37ca7243-0548-4050-bb87-3f6e6c48fef6.png)

## Details
The inflation of the translucent black background can be a very useful interface for other mechanics of this game.
Please write it in a way that is reusable for other purposes.

## Tasks
- [x] Bind Right Click
- [x] Inflate a slight tinted black background above the game
- [x] Lock Game input until clicked outside of the displayed card (the tinted black background)
- [x] Inflate a higher resolution card in the middle

**Comment by Bratah123** [comment]
Added in Commit: https://github.com/BAA-Studios/MOOgiwara/commit/cee73a5589984010f58393a08ae7d6c578f9fb28
