### ISSUE TITLE
[TODO] Game Board: Attacking

### ISSUE THREAD

**Issue by Bratah123** [BAA-Studios/MOOgiwara#41]
## Abstract
This issue will address attacking other character/leader cards with a character card.

## Details
When left-clicking an `unrested` card, allow for users to see an arrow where they can choose an unrested character to attack.

The card must not be effected by summoning sickness.

Character/Leaders are only allowed to attack `rested` cards, (unless its the leader).
Display how much the character is attacking for. (Whether there is Don!! attached or not)

For the sake of simplicity, this issue will not tackle the counter step phase of an attack instance.

## Tasks
- [x] Rendering the arrow
- [x] Left-Clicking
- [x] Selecting an enemy character/leader
- [x] Render Green Highlight over cards that are attackable
- [x] Rest the character that is attacking
- [x] Broadcast the attack to the opponent

**Comment by Bratah123** [comment]
Current Sequencing and Demo of Attacking/Blocking:

https://user-images.githubusercontent.com/58405975/217667287-3b9a76de-8a44-4bd2-abc1-2e81ba26c3d9.mp4

This demo is applicable to #52
