### ISSUE TITLE
[TODO] Game Board: Trash

### ISSUE THREAD

**Issue by Bratah123** [BAA-Studios/MOOgiwara#46]
## Abstract
This handles the cards in the Trash. The last card trashed should be displayed on top.

## Details
When event cards are played, place them in the trash after resolving their effects.
When a character card gets knocked out.
When cards are played in response to an attack (counter phase).

The entire trash should be able to be displayed to the entire screen when clicked on.

## Tasks
- [x] Render the trash
- [x] Clicking on the trash shows a list of cards.
- [x] Make the Trash Scrollable or Add Pages when the cards fill the screen
- [x] Broadcast same information for opponent

**Comment by Bratah123** [comment]
MVP Demo of Trash Viewing Mechanic

https://user-images.githubusercontent.com/58405975/215632861-dd3e5782-7de8-49ca-b27d-7a261724a2b1.mp4

**Comment by Bratah123** [comment]
Demo of networked trash (able to see opponent's trash
https://user-images.githubusercontent.com/58405975/216152037-6431c425-aa69-4651-9104-52d701f86e33.mp4

**Comment by Bratah123** [comment]
@ta-lyx please take a look at the unchecked item in the checklist on your free time :)

Implementing a scrolling OR a Pages feature to the trash would be very nice!

**Comment by Bratah123** [comment]
https://user-images.githubusercontent.com/58405975/223598894-37d9597e-49df-4037-9f8d-c56eac9c63b4.mp4

Final Demo of Trash Mechanic
