### ISSUE TITLE
[TODO] Logging Game Actions

### ISSUE THREAD

**Issue by Bratah123** [BAA-Studios/MOOgiwara#50]
## Abstract
The Server should log to both players in the chat when certain game actions has been done.

## Tasks
- [ ] Playing a Character Card
- [ ] Playing an Event Card
- [ ] Declaration of Attack
- [x] End Turn
- [x] Who goes first
