### ISSUE TITLE
[TODO] Game Board: Blocker Phase

### ISSUE THREAD

**Issue by Bratah123** [BAA-Studios/MOOgiwara#52]
## Abstract
This phase is after an attack has been declared, a player can choose any `Blocker` attribute characters to take place of the attack.

## Details
When attack has been declared, allow the defending player to choose/click any of their blockers to take the place of the attack.
If the defending player has no blockers, then skip immediately to Counter Phase: #42 

## Tasks
- [x] Skip to Counter phase if no blockers
- [x] Allow players to select a blocker to take the place of the attack
- [x] Don!! shouldn't account for their defense
- [x] Rest any chosen blockers
- [x] Skip Blockers Button

**Comment by Bratah123** [comment]
See #41 for a demo of this issue!
