### ISSUE TITLE
[TODO] Game Board ** Part 2 ** Board Setup

### ISSUE THREAD

**Issue by Bratah123** [BAA-Studios/MOOgiwara#8]
## Abstract
This phase of the game setup starts right at the beginning.

Both players decide will do Rock Paper Scissors to decide who goes first (or any means)
For our case, we will be using a `Heads or Tails` System to decide who goes first.

## Details
Each player draws 5 cards.
They are allowed to `mulligan` away their hand once.

This is the act of reshuffling their 5 card hand into their deck to redraw 5 new cards.

Once all of those actions are resolved, both players allocate `Life Cards` to the Life card area depending on their `Leader's` Life Points indicated on the card.

## Images
See Life Points on card bottom right.
![image](https://user-images.githubusercontent.com/58405975/205868790-4b423efe-5629-4d05-b68a-4adc637583ed.png)

See Life Card Area to left.
![image](https://user-images.githubusercontent.com/58405975/205868846-a5ff275d-fcc3-4e47-bbd6-bd7cbbffa884.png)

## Tasks
- [x] Decide which players goes first
- [x] Drawing 5 cards
- [x] Give user choice to Mulligan their hand
- [x] Set Life Cards

**Comment by Bratah123** [comment]
Finished in commit: 29bd21a1b2d2e5f7703ae8cdc7ca3b502147935e
